apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      serviceAccount: pod-service-access
      containers:
      - name: grafana
        image: my_grafana
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
          name: graf
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  ports:
  - name: graf
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
  type: LoadBalancer
