apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  labels:
    app: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
      - name: telegraf
        image: my_telegraf
        imagePullPolicy: Never
        ports:
        - containerPort: 8088
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: telegraf
spec:
  ports:
  - name: http
    port: 8088
    protocol: TCP
    targetPort: 8088
  selector:
    app: telegraf
  type: LoadBalancer
